name: opena_front
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # flutter_page_indicator: ^0.0.3
  # carousel_slider: ^2.3.1
  # dots_indicator: ^1.2.0
  http: ^0.12.2
  crypto: ^2.1.5
  modal_progress_hud: ^0.1.3
  flushbar: ^1.10.4
  countdown_flutter: ^0.1.2
  mask_text_input_formatter: ^1.1.0
  liquid_progress_indicator: ^0.3.2
  # cupertino_stepper: ^0.1.2
  pattern_formatter: ^1.0.2
  image_picker: ^0.6.7+12
  im_stepper: ^0.1.2+6
  permission_handler: ^5.0.1+1
  app_settings: ^4.0.4
  multi_image_picker: ^4.7.14
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: asset/fonts/Pacifico-Regular.ttf


